### YamlMime:ManagedReference
items:
- uid: SadConsole.Settings.WindowResizeOptions
  commentId: T:SadConsole.Settings.WindowResizeOptions
  id: Settings.WindowResizeOptions
  parent: SadConsole
  children:
  - SadConsole.Settings.WindowResizeOptions.Center
  - SadConsole.Settings.WindowResizeOptions.Fit
  - SadConsole.Settings.WindowResizeOptions.None
  - SadConsole.Settings.WindowResizeOptions.Scale
  - SadConsole.Settings.WindowResizeOptions.Stretch
  langs:
  - csharp
  - vb
  name: Settings.WindowResizeOptions
  nameWithType: Settings.WindowResizeOptions
  fullName: SadConsole.Settings.WindowResizeOptions
  type: Enum
  assemblies:
  - SadConsole
  namespace: SadConsole
  summary: Resize modes for the final SadConsole render pass.
  example: []
  syntax:
    content: public enum Settings.WindowResizeOptions
    content.vb: Public Enum Settings.WindowResizeOptions
- uid: SadConsole.Settings.WindowResizeOptions.Stretch
  commentId: F:SadConsole.Settings.WindowResizeOptions.Stretch
  id: Stretch
  parent: SadConsole.Settings.WindowResizeOptions
  langs:
  - csharp
  - vb
  name: Stretch
  nameWithType: Settings.WindowResizeOptions.Stretch
  fullName: SadConsole.Settings.WindowResizeOptions.Stretch
  type: Field
  assemblies:
  - SadConsole
  namespace: SadConsole
  summary: Stretches the output to fit the window.
  example: []
  syntax:
    content: Stretch = 0
    return:
      type: SadConsole.Settings.WindowResizeOptions
- uid: SadConsole.Settings.WindowResizeOptions.Center
  commentId: F:SadConsole.Settings.WindowResizeOptions.Center
  id: Center
  parent: SadConsole.Settings.WindowResizeOptions
  langs:
  - csharp
  - vb
  name: Center
  nameWithType: Settings.WindowResizeOptions.Center
  fullName: SadConsole.Settings.WindowResizeOptions.Center
  type: Field
  assemblies:
  - SadConsole
  namespace: SadConsole
  summary: Centers output in the window.
  example: []
  syntax:
    content: Center = 1
    return:
      type: SadConsole.Settings.WindowResizeOptions
- uid: SadConsole.Settings.WindowResizeOptions.Scale
  commentId: F:SadConsole.Settings.WindowResizeOptions.Scale
  id: Scale
  parent: SadConsole.Settings.WindowResizeOptions
  langs:
  - csharp
  - vb
  name: Scale
  nameWithType: Settings.WindowResizeOptions.Scale
  fullName: SadConsole.Settings.WindowResizeOptions.Scale
  type: Field
  assemblies:
  - SadConsole
  namespace: SadConsole
  summary: Scales output to fit the window as best as possible while maintaining a good picture.
  example: []
  syntax:
    content: Scale = 2
    return:
      type: SadConsole.Settings.WindowResizeOptions
- uid: SadConsole.Settings.WindowResizeOptions.Fit
  commentId: F:SadConsole.Settings.WindowResizeOptions.Fit
  id: Fit
  parent: SadConsole.Settings.WindowResizeOptions
  langs:
  - csharp
  - vb
  name: Fit
  nameWithType: Settings.WindowResizeOptions.Fit
  fullName: SadConsole.Settings.WindowResizeOptions.Fit
  type: Field
  assemblies:
  - SadConsole
  namespace: SadConsole
  summary: Fits output to the window using padding to maintain aspect ratio.
  example: []
  syntax:
    content: Fit = 3
    return:
      type: SadConsole.Settings.WindowResizeOptions
- uid: SadConsole.Settings.WindowResizeOptions.None
  commentId: F:SadConsole.Settings.WindowResizeOptions.None
  id: None
  parent: SadConsole.Settings.WindowResizeOptions
  langs:
  - csharp
  - vb
  name: None
  nameWithType: Settings.WindowResizeOptions.None
  fullName: SadConsole.Settings.WindowResizeOptions.None
  type: Field
  assemblies:
  - SadConsole
  namespace: SadConsole
  summary: Output always matches the window.
  example: []
  syntax:
    content: None = 4
    return:
      type: SadConsole.Settings.WindowResizeOptions
references:
- uid: SadConsole
  commentId: N:SadConsole
  isExternal: true
  href: SadConsole.html
  name: SadConsole
  nameWithType: SadConsole
  fullName: SadConsole
- uid: SadConsole.Settings.WindowResizeOptions
  commentId: T:SadConsole.Settings.WindowResizeOptions
  parent: SadConsole
  isExternal: true
  href: SadConsole.Settings.html
  name: Settings.WindowResizeOptions
  nameWithType: Settings.WindowResizeOptions
  fullName: SadConsole.Settings.WindowResizeOptions
  spec.csharp:
  - uid: SadConsole.Settings
    name: Settings
    isExternal: true
    href: SadConsole.Settings.html
  - name: .
  - uid: SadConsole.Settings.WindowResizeOptions
    name: WindowResizeOptions
    isExternal: true
    href: SadConsole.Settings.WindowResizeOptions.html
  spec.vb:
  - uid: SadConsole.Settings
    name: Settings
    isExternal: true
    href: SadConsole.Settings.html
  - name: .
  - uid: SadConsole.Settings.WindowResizeOptions
    name: WindowResizeOptions
    isExternal: true
    href: SadConsole.Settings.WindowResizeOptions.html
