### YamlMime:ManagedReference
items:
- uid: SadConsole.Settings.Rendering
  commentId: T:SadConsole.Settings.Rendering
  id: Settings.Rendering
  parent: SadConsole
  children:
  - SadConsole.Settings.Rendering.RenderHeight
  - SadConsole.Settings.Rendering.RenderRect
  - SadConsole.Settings.Rendering.RenderScale
  - SadConsole.Settings.Rendering.RenderWidth
  langs:
  - csharp
  - vb
  name: Settings.Rendering
  nameWithType: Settings.Rendering
  fullName: SadConsole.Settings.Rendering
  type: Class
  assemblies:
  - SadConsole
  namespace: SadConsole
  summary: Rendering options generally set by a game host.
  example: []
  syntax:
    content: public static class Settings.Rendering
    content.vb: Public Module Settings.Rendering
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
- uid: SadConsole.Settings.Rendering.RenderWidth
  commentId: P:SadConsole.Settings.Rendering.RenderWidth
  id: RenderWidth
  parent: SadConsole.Settings.Rendering
  langs:
  - csharp
  - vb
  name: RenderWidth
  nameWithType: Settings.Rendering.RenderWidth
  fullName: SadConsole.Settings.Rendering.RenderWidth
  type: Property
  assemblies:
  - SadConsole
  namespace: SadConsole
  summary: The width of the area to render on the game window.
  example: []
  syntax:
    content: public static int RenderWidth { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Shared Property RenderWidth As Integer
  overload: SadConsole.Settings.Rendering.RenderWidth*
- uid: SadConsole.Settings.Rendering.RenderHeight
  commentId: P:SadConsole.Settings.Rendering.RenderHeight
  id: RenderHeight
  parent: SadConsole.Settings.Rendering
  langs:
  - csharp
  - vb
  name: RenderHeight
  nameWithType: Settings.Rendering.RenderHeight
  fullName: SadConsole.Settings.Rendering.RenderHeight
  type: Property
  assemblies:
  - SadConsole
  namespace: SadConsole
  summary: The height of the area to render on the game window.
  example: []
  syntax:
    content: public static int RenderHeight { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Shared Property RenderHeight As Integer
  overload: SadConsole.Settings.Rendering.RenderHeight*
- uid: SadConsole.Settings.Rendering.RenderRect
  commentId: P:SadConsole.Settings.Rendering.RenderRect
  id: RenderRect
  parent: SadConsole.Settings.Rendering
  langs:
  - csharp
  - vb
  name: RenderRect
  nameWithType: Settings.Rendering.RenderRect
  fullName: SadConsole.Settings.Rendering.RenderRect
  type: Property
  assemblies:
  - SadConsole
  namespace: SadConsole
  summary: Where on the screen the engine will be rendered.
  example: []
  syntax:
    content: public static Rectangle RenderRect { get; set; }
    parameters: []
    return:
      type: SadRogue.Primitives.Rectangle
    content.vb: Public Shared Property RenderRect As Rectangle
  overload: SadConsole.Settings.Rendering.RenderRect*
- uid: SadConsole.Settings.Rendering.RenderScale
  commentId: P:SadConsole.Settings.Rendering.RenderScale
  id: RenderScale
  parent: SadConsole.Settings.Rendering
  langs:
  - csharp
  - vb
  name: RenderScale
  nameWithType: Settings.Rendering.RenderScale
  fullName: SadConsole.Settings.Rendering.RenderScale
  type: Property
  assemblies:
  - SadConsole
  namespace: SadConsole
  summary: If the <xref href="SadConsole.Settings.Rendering.RenderRect" data-throw-if-not-resolved="false"></xref> is stretched, this is the ratio difference between unstretched.
  example: []
  syntax:
    content: public static (float X, float Y) RenderScale { get; set; }
    parameters: []
    return:
      type: System.ValueTuple{System.Single,System.Single}
    content.vb: Public Shared Property RenderScale As (X As Single, Y As Single)
  overload: SadConsole.Settings.Rendering.RenderScale*
references:
- uid: SadConsole
  commentId: N:SadConsole
  isExternal: true
  href: SadConsole.html
  name: SadConsole
  nameWithType: SadConsole
  fullName: SadConsole
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: SadConsole.Settings.Rendering.RenderWidth*
  commentId: Overload:SadConsole.Settings.Rendering.RenderWidth
  isExternal: true
  href: SadConsole.Settings.Rendering.html#SadConsole_Settings_Rendering_RenderWidth
  name: RenderWidth
  nameWithType: Settings.Rendering.RenderWidth
  fullName: SadConsole.Settings.Rendering.RenderWidth
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: SadConsole.Settings.Rendering.RenderHeight*
  commentId: Overload:SadConsole.Settings.Rendering.RenderHeight
  isExternal: true
  href: SadConsole.Settings.Rendering.html#SadConsole_Settings_Rendering_RenderHeight
  name: RenderHeight
  nameWithType: Settings.Rendering.RenderHeight
  fullName: SadConsole.Settings.Rendering.RenderHeight
- uid: SadConsole.Settings.Rendering.RenderRect*
  commentId: Overload:SadConsole.Settings.Rendering.RenderRect
  isExternal: true
  href: SadConsole.Settings.Rendering.html#SadConsole_Settings_Rendering_RenderRect
  name: RenderRect
  nameWithType: Settings.Rendering.RenderRect
  fullName: SadConsole.Settings.Rendering.RenderRect
- uid: SadRogue.Primitives.Rectangle
  commentId: T:SadRogue.Primitives.Rectangle
  parent: SadRogue.Primitives
  isExternal: true
  name: Rectangle
  nameWithType: Rectangle
  fullName: SadRogue.Primitives.Rectangle
- uid: SadRogue.Primitives
  commentId: N:SadRogue.Primitives
  isExternal: true
  href: SadRogue.html
  name: SadRogue.Primitives
  nameWithType: SadRogue.Primitives
  fullName: SadRogue.Primitives
  spec.csharp:
  - uid: SadRogue
    name: SadRogue
    isExternal: true
    href: SadRogue.html
  - name: .
  - uid: SadRogue.Primitives
    name: Primitives
    isExternal: true
    href: SadRogue.Primitives.html
  spec.vb:
  - uid: SadRogue
    name: SadRogue
    isExternal: true
    href: SadRogue.html
  - name: .
  - uid: SadRogue.Primitives
    name: Primitives
    isExternal: true
    href: SadRogue.Primitives.html
- uid: SadConsole.Settings.Rendering.RenderRect
  commentId: P:SadConsole.Settings.Rendering.RenderRect
  isExternal: true
  href: SadConsole.Settings.Rendering.html#SadConsole_Settings_Rendering_RenderRect
  name: RenderRect
  nameWithType: Settings.Rendering.RenderRect
  fullName: SadConsole.Settings.Rendering.RenderRect
- uid: SadConsole.Settings.Rendering.RenderScale*
  commentId: Overload:SadConsole.Settings.Rendering.RenderScale
  isExternal: true
  href: SadConsole.Settings.Rendering.html#SadConsole_Settings_Rendering_RenderScale
  name: RenderScale
  nameWithType: Settings.Rendering.RenderScale
  fullName: SadConsole.Settings.Rendering.RenderScale
- uid: System.ValueTuple{System.Single,System.Single}
  commentId: T:System.ValueTuple{System.Single,System.Single}
  parent: System
  definition: System.ValueTuple`2
  href: https://learn.microsoft.com/dotnet/api/system.single
  name: (float X, float Y)
  nameWithType: (float X, float Y)
  fullName: (float X, float Y)
  nameWithType.vb: (X As Single, Y As Single)
  fullName.vb: (X As Single, Y As Single)
  name.vb: (X As Single, Y As Single)
  spec.csharp:
  - name: (
  - uid: System.Single
    name: float
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.single
  - name: " "
  - uid: System.ValueTuple{System.Single,System.Single}.X
    name: X
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetuple-system.single,system.single-.x
  - name: ','
  - name: " "
  - uid: System.Single
    name: float
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.single
  - name: " "
  - uid: System.ValueTuple{System.Single,System.Single}.Y
    name: Y
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetuple-system.single,system.single-.y
  - name: )
  spec.vb:
  - name: (
  - uid: System.ValueTuple{System.Single,System.Single}.X
    name: X
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetuple-system.single,system.single-.x
  - name: " "
  - name: As
  - name: " "
  - uid: System.Single
    name: Single
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.single
  - name: ','
  - name: " "
  - uid: System.ValueTuple{System.Single,System.Single}.Y
    name: Y
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetuple-system.single,system.single-.y
  - name: " "
  - name: As
  - name: " "
  - uid: System.Single
    name: Single
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.single
  - name: )
- uid: System.ValueTuple`2
  commentId: T:System.ValueTuple`2
  name: (T1, T2)
  nameWithType: (T1, T2)
  fullName: (T1, T2)
  spec.csharp:
  - name: (
  - name: T1
  - name: ','
  - name: " "
  - name: T2
  - name: )
  spec.vb:
  - name: (
  - name: T1
  - name: ','
  - name: " "
  - name: T2
  - name: )
