### YamlMime:ManagedReference
items:
- uid: SadConsole.Settings.Input
  commentId: T:SadConsole.Settings.Input
  id: Settings.Input
  parent: SadConsole
  children:
  - SadConsole.Settings.Input.DoKeyboard
  - SadConsole.Settings.Input.DoMouse
  - SadConsole.Settings.Input.MouseClickTime
  - SadConsole.Settings.Input.MouseDoubleClickTime
  - SadConsole.Settings.Input.ProcessMouseOffscreen
  langs:
  - csharp
  - vb
  name: Settings.Input
  nameWithType: Settings.Input
  fullName: SadConsole.Settings.Input
  type: Class
  assemblies:
  - SadConsole
  namespace: SadConsole
  summary: Settings related to input.
  example: []
  syntax:
    content: public static class Settings.Input
    content.vb: Public Module Settings.Input
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
- uid: SadConsole.Settings.Input.ProcessMouseOffscreen
  commentId: P:SadConsole.Settings.Input.ProcessMouseOffscreen
  id: ProcessMouseOffscreen
  parent: SadConsole.Settings.Input
  langs:
  - csharp
  - vb
  name: ProcessMouseOffscreen
  nameWithType: Settings.Input.ProcessMouseOffscreen
  fullName: SadConsole.Settings.Input.ProcessMouseOffscreen
  type: Property
  assemblies:
  - SadConsole
  namespace: SadConsole
  summary: Not currently used
  example: []
  syntax:
    content: public static bool ProcessMouseOffscreen { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Shared Property ProcessMouseOffscreen As Boolean
  overload: SadConsole.Settings.Input.ProcessMouseOffscreen*
- uid: SadConsole.Settings.Input.DoMouse
  commentId: P:SadConsole.Settings.Input.DoMouse
  id: DoMouse
  parent: SadConsole.Settings.Input
  langs:
  - csharp
  - vb
  name: DoMouse
  nameWithType: Settings.Input.DoMouse
  fullName: SadConsole.Settings.Input.DoMouse
  type: Property
  assemblies:
  - SadConsole
  namespace: SadConsole
  summary: Indicates that the <xref href="SadConsole.GameHost" data-throw-if-not-resolved="false"></xref> should process mouse input.
  example: []
  syntax:
    content: public static bool DoMouse { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Shared Property DoMouse As Boolean
  overload: SadConsole.Settings.Input.DoMouse*
- uid: SadConsole.Settings.Input.DoKeyboard
  commentId: P:SadConsole.Settings.Input.DoKeyboard
  id: DoKeyboard
  parent: SadConsole.Settings.Input
  langs:
  - csharp
  - vb
  name: DoKeyboard
  nameWithType: Settings.Input.DoKeyboard
  fullName: SadConsole.Settings.Input.DoKeyboard
  type: Property
  assemblies:
  - SadConsole
  namespace: SadConsole
  summary: Indicates that the <xref href="SadConsole.GameHost" data-throw-if-not-resolved="false"></xref> should process keyboard input.
  example: []
  syntax:
    content: public static bool DoKeyboard { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Shared Property DoKeyboard As Boolean
  overload: SadConsole.Settings.Input.DoKeyboard*
- uid: SadConsole.Settings.Input.MouseClickTime
  commentId: P:SadConsole.Settings.Input.MouseClickTime
  id: MouseClickTime
  parent: SadConsole.Settings.Input
  langs:
  - csharp
  - vb
  name: MouseClickTime
  nameWithType: Settings.Input.MouseClickTime
  fullName: SadConsole.Settings.Input.MouseClickTime
  type: Property
  assemblies:
  - SadConsole
  namespace: SadConsole
  summary: The maximum amount of time to trigger a mouse click.
  example: []
  syntax:
    content: public static TimeSpan MouseClickTime { get; set; }
    parameters: []
    return:
      type: System.TimeSpan
    content.vb: Public Shared Property MouseClickTime As TimeSpan
  overload: SadConsole.Settings.Input.MouseClickTime*
- uid: SadConsole.Settings.Input.MouseDoubleClickTime
  commentId: P:SadConsole.Settings.Input.MouseDoubleClickTime
  id: MouseDoubleClickTime
  parent: SadConsole.Settings.Input
  langs:
  - csharp
  - vb
  name: MouseDoubleClickTime
  nameWithType: Settings.Input.MouseDoubleClickTime
  fullName: SadConsole.Settings.Input.MouseDoubleClickTime
  type: Property
  assemblies:
  - SadConsole
  namespace: SadConsole
  summary: The maximum amount of time to trigger a mouse double click.
  example: []
  syntax:
    content: public static TimeSpan MouseDoubleClickTime { get; set; }
    parameters: []
    return:
      type: System.TimeSpan
    content.vb: Public Shared Property MouseDoubleClickTime As TimeSpan
  overload: SadConsole.Settings.Input.MouseDoubleClickTime*
references:
- uid: SadConsole
  commentId: N:SadConsole
  isExternal: true
  href: SadConsole.html
  name: SadConsole
  nameWithType: SadConsole
  fullName: SadConsole
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: SadConsole.Settings.Input.ProcessMouseOffscreen*
  commentId: Overload:SadConsole.Settings.Input.ProcessMouseOffscreen
  isExternal: true
  href: SadConsole.Settings.Input.html#SadConsole_Settings_Input_ProcessMouseOffscreen
  name: ProcessMouseOffscreen
  nameWithType: Settings.Input.ProcessMouseOffscreen
  fullName: SadConsole.Settings.Input.ProcessMouseOffscreen
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: SadConsole.GameHost
  commentId: T:SadConsole.GameHost
  parent: SadConsole
  isExternal: true
  href: SadConsole.GameHost.html
  name: GameHost
  nameWithType: GameHost
  fullName: SadConsole.GameHost
- uid: SadConsole.Settings.Input.DoMouse*
  commentId: Overload:SadConsole.Settings.Input.DoMouse
  isExternal: true
  href: SadConsole.Settings.Input.html#SadConsole_Settings_Input_DoMouse
  name: DoMouse
  nameWithType: Settings.Input.DoMouse
  fullName: SadConsole.Settings.Input.DoMouse
- uid: SadConsole.Settings.Input.DoKeyboard*
  commentId: Overload:SadConsole.Settings.Input.DoKeyboard
  isExternal: true
  href: SadConsole.Settings.Input.html#SadConsole_Settings_Input_DoKeyboard
  name: DoKeyboard
  nameWithType: Settings.Input.DoKeyboard
  fullName: SadConsole.Settings.Input.DoKeyboard
- uid: SadConsole.Settings.Input.MouseClickTime*
  commentId: Overload:SadConsole.Settings.Input.MouseClickTime
  isExternal: true
  href: SadConsole.Settings.Input.html#SadConsole_Settings_Input_MouseClickTime
  name: MouseClickTime
  nameWithType: Settings.Input.MouseClickTime
  fullName: SadConsole.Settings.Input.MouseClickTime
- uid: System.TimeSpan
  commentId: T:System.TimeSpan
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.timespan
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: SadConsole.Settings.Input.MouseDoubleClickTime*
  commentId: Overload:SadConsole.Settings.Input.MouseDoubleClickTime
  isExternal: true
  href: SadConsole.Settings.Input.html#SadConsole_Settings_Input_MouseDoubleClickTime
  name: MouseDoubleClickTime
  nameWithType: Settings.Input.MouseDoubleClickTime
  fullName: SadConsole.Settings.Input.MouseDoubleClickTime
